# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  server:
    build:
      context: .
      target: development
    ports:
      - 9000:80
    depends_on:
      mysql-db:
        condition: service_healthy
      pgsql-db:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: ./src
          target: /var/www/html

  mysql-db:
    image: docker.io/library/mysql
    restart: always
    volumes:
      - mysql-db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=edaha
      - MYSQL_USER=edaha
      - MYSQL_PASSWORD=edaha
      - MYSQL_ROOT_PASSWORD=edaha
    ports:
      - 3306:3306
    expose:
      - 3306
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
  
  pgsql-db:
    image: docker.io/library/postgres
    restart: always
    user: postgres
    volumes:
      - pgsql-db-data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=edaha
      - POSTGRES_USER=edaha
      - POSTGRES_PASSWORD=edaha
    ports:
      - 5432:5432
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  mysql-db-data:
  pgsql-db-data:

